### ISSUE TITLE
Arcade Rev B Fixes

### ISSUE THREAD

**Issue by radioshadow** [Nasina7/puyodisasm#3]
So in the Arcade Rev A version:
- A bug where the AI loses its ability to manually drop Puyo if the other joystick is held to the left or right.
- Only select 28 letters instead of 29 letters when pressing UP on the BEST RECORD board.

These were fixed in Arcade Rev B version. The Mega Drive port was based on Rev A, so the bugs still occur. I managed to find the code that was changed, and have located what needs to be changed in the Mega Drive rom.

Include a setting that allows the user to compile the Rev B changes. See notes below:

--------------------

Puyo - Arcade (REV A)

E9CC = andi.w   #$FD8F, D0
E9D0 = andi.b   #$F3, D1

A1B0 = move.b   #$1C, ($12, A0, d0.w)

--------------------

Puyo - Arcade (REV B)

E9CC = andi.w   #0, D0
E9D0 = andi.b   #0, D1

A1B0 = move.b   #$1B, ($12, A0, d0.w)

--------------------

Puyo - Mega Drive

1009C = andi.w   #$FD8F, D0
100A0 = andi.b   #$F3, D1

 B900 = move.b   #$1C, ($12, A0, d0.w)

--------------------

Puyo - Mega Drive (Fix Issues)

1009C = andi.w   #0, D0
100A0 = andi.b   #0, D1

 B900 = move.b   #$1B, ($12, A0, d0.w)

--------------------

**Comment by Nasina7** [comment]
Ooh, nice.  I've been wondering what the fix for that first one was (never even knew that second one existed lol).  I'll implement this next commit :+1:

**Comment by Nasina7** [comment]
Implemented in commit 87e6692.
