### ISSUE TITLE
unkCharset#.bin compress graphics - Move to correct location

### ISSUE THREAD

**Issue by radioshadow** [Nasina7/puyodisasm#4]
So Lessons 1-3, Lesson End, and Stages 1-13 all use a separate font set. The "unkCharset#.bin" files can be renamed and put in the correct folders.

The Tutorial and Story Ending do use a different font set, but these are stored with the other graphics.

So the "unkCharset4.bin" you have in the Unknown folder is the Lesson End font. So there is nothing unknown about it. :P

loc_00009504:
	dc.l	art_cutsceneSkeletonT
	dc.l	art_cutsceneSuketoudara
	dc.l	art_cutsceneZombie
	dc.l	art_cutsceneDraco
	dc.l	art_cutsceneNasuGrave
	dc.l	art_cutsceneWitch
	dc.l	art_cutsceneSasoriman
	dc.l	art_cutsceneHarpy
	dc.l	art_cutsceneZoh
	dc.l	art_cutsceneSchezo
	dc.l	art_cutsceneMinotauros
	dc.l	art_cutsceneRulue
	dc.l	art_cutsceneSatan
	dc.l	art_cutsceneMummy
	dc.l	art_cutsceneSukiyapotes
	dc.l	art_cutscenePanotty
	dc.l	art_cutsceneSatan
	dc.l	art_cutsceneCharset_tutorial1	; Lesson 1
	dc.l	loc_00047374			; Stage 2
	dc.l	loc_0004700E			; Stage 7
	dc.l	art_cutsceneCharset_stage1	; Stage 1
	dc.l	loc_0004B2DE			; Lesson 2
	dc.l	loc_00048FBA			; Stage 8
	dc.l	loc_00048ABC			; Stage 5
	dc.l	loc_00049DE6			; Stage 4
	dc.l	loc_000476DC			; Stage 9
	dc.l	loc_0004A13E			; Stage 10
	dc.l	loc_000483D6			; Stage 11
	dc.l	loc_00049576			; Stage 12
	dc.l	loc_0004A9B0			; Stage 13
	dc.l	loc_0004B548			; Lesson 3
	dc.l	loc_0004B9C8			; Stage 3
	dc.l	loc_0004BEF0			; Stage 6
	dc.l	loc_00028500			; Lesson End

However, the "unrefCharset.bin" is an interesting find. It is set up the same way as the Tutorial font (where the background color uses bit 0, while the dialog font set uses bit 1). Which means it would have been used on the Battle Board. Maybe it was gonna be used for the Mission Mode, or maybe a Lesson Mode (hence the letters)?

**Comment by Nasina7** [comment]
Nice, will get that fixed soon.  :+1: 

The unreferenced charset was definitely an interesting find.  Randomly found it while working on a tool for the art compression format a while back and had no idea what it was :p

**Comment by Nasina7** [comment]
Fixed in commit 7769ed5.
