### ISSUE TITLE
segaLogo.bin - Seperate Unused Mappings

### ISSUE THREAD

**Issue by radioshadow** [Nasina7/puyodisasm#6]
Looking at the "segaLogo.bin" file in "art > uncompressed", I noticed some data at hex location 600. I thought it was the mappings for the logo, but there is already a mappings in: bgMappings > sega > logo.bin

The "logo.bin" is the one game uses. This one uses 1 byte per tile to represent which tile to load.

The data at the end of "segaLogo.bin" is also the same mapping data, but uses 1 word (2 bytes) per tile to represent which tile to load. The game doesn't use this mapping. Just data that is taking up space.

If you could separate this unused mapping from the "segaLogo.bin" file, and place it in with the "logo.bin" file (maybe call it logo_unused), that would be great.

**Comment by Nasina7** [comment]
Nice find!  I'll fix this next commit.

**Comment by Nasina7** [comment]
Fixed in commit ed1b3d9.
